config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :videos do
    member do 
      get :play
      put :update_views
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :videos
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user

  validates :name, :url, presence: true
  validate :check_video_url_extension

  private

  def check_video_url_extension
    unless !url.nil? && url.match?('.m3u8$')
      errors.add(:video, I18n.t(:url_extension_should_be_m3u8, scope: 'errors.messages'))
      throw :abort
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, unless: :public_page?

  layout :layout_by_resource

  def after_sign_in_path_for(resource)
    videos_path
  end

  def layout_by_resource
    if devise_controller?
      'login'
    elsif public_page?
      'clean'
    else
      'application'
    end
  end

  def public_page?
    request.fullpath.match?('/play') || request.fullpath.match?('/update_views')
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:update_views]
  before_action :set_video, only: [:show, :edit, :update, :destroy, :play, :update_views]

  respond_to :html, :js

  def index
    @videos = current_user.videos.paginate(per_page: 9, page: params[:page])

    respond_with @videos
  end

  def show
    respond_with @video
  end

  def new
    @video = current_user.videos.new

    respond_with @video
  end

  def edit
    respond_with @video
  end

  def create
    @video = current_user.videos.new(video_params)
    flash[:notice] = I18n.t(:created_resource, resource: I18n.t(:video, scope: "activerecord.models")) if @video.save

    respond_with @video
  end

  def update
    flash[:notice] = I18n.t(:updated_resource, resource: I18n.t(:video, scope: "activerecord.models")) if @video.update(video_params)
    
    respond_with @video
  end

  def destroy
    flash[:notice] = I18n.t(:destroyed_resource, resource: I18n.t(:video, scope: "activerecord.models")) if @video.destroy

    respond_with @video, :location => videos_url
  end

  def play
    respond_with @video
  end

  def update_views
    @video.update(views: @video.views + 1)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_video
    @video = Video.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def video_params
    params.require(:video).permit(
      :name,
      :url
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Netshow.me</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link href="https://fonts.googleapis.com/css?family=Baloo+Bhai&display=swap" rel="stylesheet">
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  
  <!-- Navigation -->
  <nav class="navbar navbar-expand-xl navbar-light static-top border-bottom navbar-top">
    <div class="container">
      <%= link_to root_path do %>
        <h4 class="mb-0 text-dark">Netshow.me</h4>
      <% end %>
      <ul class="navbar-nav ml-auto">
        <%= render  "shared/menu" %>
      </ul>
    </div>
  </nav>

  <div class="container">
    <div>
      <%= render partial: "shared/flashes" %>
    </div>
    <% if yield(:right).presence %>
      <div class="float-right mt-4 mr-2">
        <%= yield :right %>
      </div>
      <br/>
    <% end %>
  </div>
  <!-- Page Content -->
  <div class="container" style="margin-top: 40px;">
    <div class="card border-0 my-5" style="min-height: 550px;">
      <div class="card-body p-5 text-center">
        <%= yield %>
      </div>
    </div>
  </div>

  <%= yield :scripts %>

</body>

</html>

app/views/layouts/clean.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Netshow.me</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link href="https://fonts.googleapis.com/css?family=Baloo+Bhai&display=swap" rel="stylesheet">
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar navbar-light static-top border-bottom navbar-top">
    <div class="container">
        <%= link_to root_path do %>
          <h4 class="mb-0 text-dark">Netshow.me</h4>
        <% end %>
    </div>
  </nav>

  <div class="container">
    <div class="card border border-dark my-5">
      <div class="card-body p-5 text-center">
        <%= yield %>
      </div>
    </div>
  </div>

  <%= yield :scripts %>

</body>

</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Netshow.me</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link href="https://fonts.googleapis.com/css?family=Baloo+Bhai&display=swap" rel="stylesheet">
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="min-vh-100" style="background-image: linear-gradient(#37cbfb, #fc98ca);">

  <div class="container">
    <div>
      <%= render partial: "shared/flashes" %>
    </div>
    <div class="card border-0 my-5 col-md-4 mx-auto">
      <div class="card-body p-5 text-center">
        <%= yield %>
      </div>
    </div>
  </div>

  <%= yield :scripts %>

</body>

</html>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
  <div class="alert-container">
    <div class="alert alert-top alert-danger">
      <a class="close" data-dismiss="alert">&times;</a>
      <%= t(:default_message, scope: 'simple_form.error_notification') %><br/>
      <% resource.errors.full_messages.each do |msg| %>
        <%= msg.sub(resource.class.name, '') %><br/>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% flash.each do |name, msg| %>
  <div class="alert-container">
    <div class="alert alert-top alert-<%= name.to_s == 'notice' ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&times;</a>
      <%= msg %>
    </div>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<li class="nav-item">
  <%= link_to new_video_path, class: 'nav-link', title: t(:create_video, scope: 'menu') do %>
    <h3 class="mb-0 mr-2 text-success"><i class="fas fa-plus-circle"></i></h3>
  <% end %>
</li>

<li class="nav-item">
  <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link', title: t(:logout, scope: 'menu') do %>
    <h3 class="mb-0"><i class="fas fa-sign-out-alt"></i></h3>
  <% end %>
</li>

app/views/videos/_form.html.erb
<%= simple_form_for(@video) do |f| %>
  <%= render "shared/error_messages", resource: @video %>

  <div class="form-inputs">
  <%= f.input :name %>
  <br/>
  <%= f.input :url %>
  </div>

  <br/>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<% content_for :right do %>
  <%= link_to t(:show), @video, class: 'btn btn-primary' %>
  <%= link_to t(:back), videos_path, class: 'btn btn-primary' %>
<% end %>

<%= render 'form' %>

app/views/videos/index.html.erb
<% if @videos.any? %>
  <div class="row">
    <% @videos.each do |video| %>
      <div class="col-md-4 col-xs-12 mb-4">
        <div class="card">
          <%= link_to video do %>
            <%= image_pack_tag  "video_image.png", class: 'img-fluid' %>
          <% end %>
          <div class="card-body">
            <%= link_to video do %>
              <h5 class="card-title smooth-scroll"><%= video.name %></h5>
            <% end %>
            
            <%= link_to edit_video_path(video), class: 'btn mr-4', title: t(:edit) do %>
              <h4><i class="fas fa-edit"></i></h4>
            <% end -%>

            <%= link_to video, method: :delete, data: { confirm: "#{t(:are_you_sure)}?" }, class: 'btn', title: t(:destroy) do %>
              <h4><i class="fas fa-trash"></i></h4>
            <% end -%>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <br/>
  <div class="will_paginate">
    <%= will_paginate @videos %>
  </div>
<% else %>
  <div class="jumbotron text-black">
    Você ainda não possui nenhum vídeo!
    <br/><br/>
    <%= link_to new_video_path, class: 'nav-link', title: t(:create_video, scope: 'menu') do %>
      <button class="btn btn-primary">
        <i class="fas fa-plus-circle"></i>
        <%= t(:create_resource, resource: t(:video, scope: 'activerecord.models')) %>
      </button>
    <% end %>
  </div>
<% end %>

app/views/videos/new.html.erb
<% content_for :right do %>
  <%= link_to t(:back), videos_path, class: 'btn btn-primary' %>
<% end %>

<%= render 'form' %>

app/views/videos/play.html.erb
<video class="video-js vjs-big-play-centered vjs-16-9" controls data-setup="{}">
	<source src="<%= @video.url %>" type="application/x-mpegURL">
	<p class="vjs-no-js"><%= t(:javascript_failed) %> <a href="https://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
</video>
<br/>
<div class="row">
	<div class="col-md-9 text-left">
		<h5><strong><%= @video.name %></strong></h5>
	</div>
	<div class="col-md-3 text-right">
		<h5 class="views"><%= @video.views %> <%= t(:views, scope: 'activerecord.attributes.video') %></h5>
	</div>
	<div class="info col-12">
	</div>
</div>

<%= content_for :scripts do %> 
  <script type='text/javascript'>
		var first_view = false;
		$('video').bind('play', function (e) {
			if (first_view == false) {
				first_view = true;
				$.ajax({
					type: "PUT",
					url: "<%= update_views_video_url(@video) %>",
					cache: false,
					success: function(html){
						$(".views").html("<%= @video.views + 1 %> <%= t(:views, scope: 'activerecord.attributes.video') %>");
					},
					error: function(html){
						$(".info").append("<br/><p><%= t(:your_view_was_not_counted, scope: 'errors.messages') %></p>");
					}
				});
			}
		});
  </script>
<% end %>

app/views/videos/show.html.erb
<% content_for :right do %>
	<%= link_to t(:play), play_video_path(@video), class: 'btn btn-primary' %>
	<%= link_to t(:edit), edit_video_path(@video), class: 'btn btn-primary' %>
	<%= link_to t(:back), videos_path, class: 'btn btn-primary' %>
<% end %>

<div class="border border-dark">
	<div class="row mr-2">
		<div class="col-md-6">
			<%= image_pack_tag "video_image.png", class: 'img-fluid' %>
		</div>
		<div class="col-md-6 align-self-center">
			<h5><strong><%= t(:name, scope: 'activerecord.attributes.video') %>:</strong></h5>
			<p><%= @video.name %></p>
			<br/>
			<h5><strong><%= t(:url, scope: 'activerecord.attributes.video') %>:</strong></h5>
			<p><%= @video.url %></p>
			<br/>
			<h5><strong><%= t(:views, scope: 'activerecord.attributes.video') %>:</strong></h5>
			<p><%= @video.views %></p>
		</div>
	</div>
</div>

<br/><br/>

<div class="border border-dark h4">
	<div class="row pt-3">
		<div class="col-md-2">
			<p><%= t(:public_url, scope: 'activerecord.attributes.video') %>:</p>
		</div>
		<div class="col-md-8">
			<p id="link_copy"><%= play_video_url(@video) %></p>
		</div>
		<div class="col-md-2 text-right">
			<button id="copy" class="bg-transparent border-0"><%= t(:copy) %></button>
		</div>
	</div>
</div>

<%= content_for :scripts do %> 
  <script type='text/javascript'>
    $('#copy').click(function() {
      var aux = document.createElement("input");
      aux.setAttribute("value", document.getElementById('link_copy').innerHTML);
      document.body.appendChild(aux);    
      aux.select();
      document.execCommand("copy");
      document.body.removeChild(aux);
    })
  </script>
<% end %>